# Site Settings
baseurl: ""
url: "https://mauriciord.com.br"
paginate:            5
plugins_dir:  _plugins
# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           /:title/
plugins:             [jekyll-paginate-v2, jekyll-admin]
exclude:             ['package.json', 'src', 'node_modules']
