# Site Settings
baseurl: ""
url: "https://mauriciord.com.br"
paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           /:title/
plugins:             [jekyll-paginate,jekyll-paginate-v2]
exclude:             ['package.json', 'src', 'node_modules']
