# Site Settings

paginate:            5

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
plugins:             [jekyll-paginate,jekyll-paginate-v2]
exclude:             ['package.json', 'src', 'node_modules']
